# Site Settings
title: nimblecss.com
name: nimblecss.com
email: ajdin@nimblecss.com
description: > # this means to ignore newlines until "baseurl:"
  nimblecss.com, Blazing fast CSS framework with best DX
baseurl: "" # the subpath of your site, e.g. /blog
url: https://www.nimblecss.com # the base hostname & protocol for your site
enforce_ssl: nimblecss.com
twitter_username: nimblecss
production_url: https://www.nimblecss.com
# github_username:  jekyll

# Build settings
markdown: kramdown
# kramdown:
#   input: GFM
#   syntax_highlighter: rouge

# markdown: redcarpet
# extenstions: [fenced_code_blocks]

# permalink: /:categories/:title

#Site Details
license: ""
license-url: ""
author: "Ajdin Imsirovic"

# Jekyll Redirect From Plugin for Redirects from redirect_from in template-overviews/blog-with-sidebar
#gems:
#  - jekyll-redirect-from

plugins:
  - jekyll-sitemap
  - jekyll-redirect-from
  - jekyll-paginate
  #- jekyll-manager

# Pagination
paginate: 10
paginate_path: "articles/page:num/"

# Compile to css from this folder, :nested, :compact, :expanded, :compressed
sass:
  sass_dir: scss
  # style: :nested
  style: :compressed
